branch-defaults:
  dsp:
    environment: covid-global-hackathon-dev
    group_suffix: null
  remote-measurements:
    environment: covid-global-hackathon-prod
    group_suffix: null
global:
  application_name: covid_global_hackathon
  branch: null
  default_ec2_keyname: covid-juanfe
  default_platform: 64bit Amazon Linux 2 v3.0.0 running Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: covid-eb-deployer
  repository: null
  sc: git
  workspace_type: Application
